apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubtestapp
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: kubtestapp
  template:
    metadata:
      labels:
        app: kubtestapp
    spec:
      containers:
      - name: kubtestapp
        image: kubtestapp:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        # image: vikash95/kubtestapp:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kubtestapp
spec:
  selector:
    app: kubtestapp
  ports:
  - port: 8080
    targetPort: 5000
